language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t dc011085/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dc011085/docker-react npm run test